namespace HeimdallWeb.Domain.Enums;

public enum LogEventCode
{
    INIT_SCAN,
    SCAN_COMPLETED,
    SCAN_ERROR,
    AI_REQUEST,
    AI_RESPONSE,
    AI_RESPONSE_ERROR,
    PATH_SCAN_STARTED,
    PATH_SCAN_RESULT,
    PATH_SUSPECTED_FALLBACK,
    HEADER_SCAN,
    COOKIE_SCAN,
    SSL_SCAN,
    DB_SAVE_OK,
    DB_SAVE_ERROR,
    USER_LOGIN,
    USER_LOGIN_FAILED,
    USER_REGISTERED,
    USER_REGISTRATION_FAILED,
    USER_PROFILE_UPDATED,
    USER_ACCOUNT_DELETED,
    SCAN_HISTORY_DELETED,
    USER_STATUS_TOGGLED,
    USER_DELETED_BY_ADMIN,
    PROFILE_IMAGE_UPDATED,
    UNHANDLED_EXCEPTION
}
