// <auto-generated />
using System;
using HeimdallWeb.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeimdallWeb.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260218135651_Sprint1_RiskWeights_ScanScore")]
    partial class Sprint1_RiskWeights_ScanScore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("code");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<int?>("HistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Info")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("RemoteIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("remote_ip");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LogId")
                        .HasName("pk_tb_log");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_tb_log_code");

                    b.HasIndex("HistoryId")
                        .HasDatabaseName("ix_tb_log_history_id");

                    b.HasIndex("Level")
                        .HasDatabaseName("ix_tb_log_level");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_tb_log_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tb_log_user_id");

                    b.ToTable("tb_log", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.Finding", b =>
                {
                    b.Property<int>("FindingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("finding_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FindingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evidence");

                    b.Property<int?>("HistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("recommendation");

                    b.Property<short>("Severity")
                        .HasColumnType("smallint")
                        .HasColumnName("severity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("FindingId")
                        .HasName("pk_tb_finding");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tb_finding_created_at");

                    b.HasIndex("HistoryId")
                        .HasDatabaseName("ix_tb_finding_history_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_tb_finding_severity");

                    b.ToTable("tb_finding", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.IASummary", b =>
                {
                    b.Property<int>("IASummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ia_summary_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IASummaryId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("FindingsCritical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_critical");

                    b.Property<int>("FindingsHigh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_high");

                    b.Property<int>("FindingsLow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_low");

                    b.Property<int>("FindingsMedium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_medium");

                    b.Property<int?>("HistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    b.Property<string>("IANotes")
                        .HasColumnType("text")
                        .HasColumnName("ia_notes");

                    b.Property<string>("MainCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("main_category");

                    b.Property<string>("OverallRisk")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("overall_risk");

                    b.Property<string>("SummaryText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary_text");

                    b.Property<int>("TotalFindings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_findings");

                    b.HasKey("IASummaryId")
                        .HasName("pk_tb_ia_summary");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_tb_ia_summary_created_date");

                    b.HasIndex("HistoryId")
                        .HasDatabaseName("ix_tb_ia_summary_history_id");

                    b.HasIndex("MainCategory")
                        .HasDatabaseName("ix_tb_ia_summary_main_category");

                    b.HasIndex("OverallRisk")
                        .HasDatabaseName("ix_tb_ia_summary_overall_risk");

                    b.ToTable("tb_ia_summary", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.RiskWeight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_tb_risk_weights");

                    b.HasIndex("Category")
                        .IsUnique()
                        .HasDatabaseName("ux_tb_risk_weights_category");

                    b.ToTable("tb_risk_weights", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.ScanHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<string>("Grade")
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("grade");

                    b.Property<bool>("HasCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_completed");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("RawJsonResult")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json_result");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("target");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("HistoryId")
                        .HasName("pk_tb_history");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_tb_history_created_date");

                    b.HasIndex("HasCompleted")
                        .HasDatabaseName("ix_tb_history_has_completed");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_tb_history_public_id");

                    b.HasIndex("RawJsonResult")
                        .HasDatabaseName("ix_tb_history_raw_json_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RawJsonResult"), "gin");

                    b.HasIndex("Target")
                        .HasDatabaseName("ix_tb_history_target");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tb_history_user_id");

                    b.ToTable("tb_history", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.Technology", b =>
                {
                    b.Property<int>("TechnologyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("technology_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TechnologyId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("technology_category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("technology_description");

                    b.Property<int?>("HistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("technology_name");

                    b.Property<string>("Version")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("version");

                    b.HasKey("TechnologyId")
                        .HasName("pk_tb_technology");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_tb_technology_category");

                    b.HasIndex("HistoryId")
                        .HasDatabaseName("ix_tb_technology_history_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tb_technology_name");

                    b.ToTable("tb_technology", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile_image");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("user_type");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_tb_user");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tb_user_created_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_tb_user_email");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_tb_user_public_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_tb_user_username");

                    b.ToTable("tb_user", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.UserUsage", b =>
                {
                    b.Property<int>("UserUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_usage_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserUsageId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("RequestCounts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("request_counts");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("UserUsageId")
                        .HasName("pk_tb_user_usage");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_tb_user_usage_date");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tb_user_usage_user_id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_user_usage_user_id_date");

                    b.ToTable("tb_user_usage", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.Views.UserCategoryBreakdown", b =>
                {
                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("CategoryCount")
                        .HasColumnType("integer")
                        .HasColumnName("category_count");

                    b.Property<int>("CriticalInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("critical_in_category");

                    b.Property<int>("HighInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("high_in_category");

                    b.Property<int>("InformationalInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("informational_in_category");

                    b.Property<int>("LowInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("low_in_category");

                    b.Property<int>("MediumInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("medium_in_category");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("vw_user_category_breakdown", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.Views.UserRiskTrend", b =>
                {
                    b.Property<int>("CriticalCount")
                        .HasColumnType("integer")
                        .HasColumnName("critical_count");

                    b.Property<int>("HighCount")
                        .HasColumnType("integer")
                        .HasColumnName("high_count");

                    b.Property<int>("InformationalCount")
                        .HasColumnType("integer")
                        .HasColumnName("informational_count");

                    b.Property<int>("LowCount")
                        .HasColumnType("integer")
                        .HasColumnName("low_count");

                    b.Property<int>("MediumCount")
                        .HasColumnType("integer")
                        .HasColumnName("medium_count");

                    b.Property<DateTime>("RiskDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("risk_date");

                    b.Property<int>("ScansOnDate")
                        .HasColumnType("integer")
                        .HasColumnName("scans_on_date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("vw_user_risk_trend", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Infrastructure.Data.Views.ViewModels.AdminIASummaryStats", b =>
                {
                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("HistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    b.Property<int>("ScanCriticalCount")
                        .HasColumnType("integer")
                        .HasColumnName("scan_critical_count");

                    b.Property<int>("ScanHighCount")
                        .HasColumnType("integer")
                        .HasColumnName("scan_high_count");

                    b.Property<int>("ScanInformationalCount")
                        .HasColumnType("integer")
                        .HasColumnName("scan_informational_count");

                    b.Property<int>("ScanLowCount")
                        .HasColumnType("integer")
                        .HasColumnName("scan_low_count");

                    b.Property<int>("ScanMaxSeverity")
                        .HasColumnType("integer")
                        .HasColumnName("scan_max_severity");

                    b.Property<int>("ScanMediumCount")
                        .HasColumnType("integer")
                        .HasColumnName("scan_medium_count");

                    b.Property<int>("ScanTotalFindings")
                        .HasColumnType("integer")
                        .HasColumnName("scan_total_findings");

                    b.ToTable((string)null);

                    b.ToView("vw_admin_ia_summary_stats", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Infrastructure.Data.Views.ViewModels.AdminMostVulnerableTargets", b =>
                {
                    b.Property<int>("HighestRiskLevel")
                        .HasColumnType("integer")
                        .HasColumnName("highest_risk_level");

                    b.Property<DateTime>("LastScanDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scan_date");

                    b.Property<int>("ScanCount")
                        .HasColumnType("integer")
                        .HasColumnName("scan_count");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.Property<int>("TotalCritical")
                        .HasColumnType("integer")
                        .HasColumnName("total_critical");

                    b.Property<int>("TotalFindings")
                        .HasColumnType("integer")
                        .HasColumnName("total_findings");

                    b.Property<int>("TotalHigh")
                        .HasColumnType("integer")
                        .HasColumnName("total_high");

                    b.Property<int>("TotalMedium")
                        .HasColumnType("integer")
                        .HasColumnName("total_medium");

                    b.ToTable((string)null);

                    b.ToView("vw_admin_most_vulnerable_targets", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Infrastructure.Data.Views.ViewModels.AdminRiskDistributionDaily", b =>
                {
                    b.Property<int>("CriticalFindings")
                        .HasColumnType("integer")
                        .HasColumnName("critical_findings");

                    b.Property<int>("HighFindings")
                        .HasColumnType("integer")
                        .HasColumnName("high_findings");

                    b.Property<int>("InformationalFindings")
                        .HasColumnType("integer")
                        .HasColumnName("informational_findings");

                    b.Property<int>("LowFindings")
                        .HasColumnType("integer")
                        .HasColumnName("low_findings");

                    b.Property<int>("MediumFindings")
                        .HasColumnType("integer")
                        .HasColumnName("medium_findings");

                    b.Property<DateTime>("RiskDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("risk_date");

                    b.Property<int>("TotalScans")
                        .HasColumnType("integer")
                        .HasColumnName("total_scans");

                    b.ToTable((string)null);

                    b.ToView("vw_admin_risk_distribution_daily", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Infrastructure.Data.Views.ViewModels.AdminTopCategories", b =>
                {
                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("CriticalInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("critical_in_category");

                    b.Property<int>("HighInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("high_in_category");

                    b.Property<int>("LowInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("low_in_category");

                    b.Property<int>("MediumInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("medium_in_category");

                    b.Property<decimal>("PercentageOfTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("percentage_of_total");

                    b.Property<int>("TotalFindingsInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("total_findings_in_category");

                    b.ToTable((string)null);

                    b.ToView("vw_admin_top_categories", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Infrastructure.Data.Views.ViewModels.DashboardLogsOverview", b =>
                {
                    b.Property<int>("LogsErrorsLast24h")
                        .HasColumnType("integer")
                        .HasColumnName("logs_errors_last_24h");

                    b.Property<int>("LogsInfoLast24h")
                        .HasColumnType("integer")
                        .HasColumnName("logs_info_last_24h");

                    b.Property<int>("LogsToday")
                        .HasColumnType("integer")
                        .HasColumnName("logs_today");

                    b.Property<int>("LogsWarnLast24h")
                        .HasColumnType("integer")
                        .HasColumnName("logs_warn_last_24h");

                    b.Property<int>("TotalLogs")
                        .HasColumnType("integer")
                        .HasColumnName("total_logs");

                    b.ToTable((string)null);

                    b.ToView("vw_dashboard_logs_overview", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Infrastructure.Data.Views.ViewModels.DashboardRecentActivity", b =>
                {
                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("RemoteIp")
                        .HasColumnType("text")
                        .HasColumnName("remote_ip");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.ToTable((string)null);

                    b.ToView("vw_dashboard_recent_activity", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Infrastructure.Data.Views.ViewModels.DashboardScanStats", b =>
                {
                    b.Property<double>("AvgScanTimeS")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_scan_time_s");

                    b.Property<decimal>("FailRate")
                        .HasColumnType("numeric")
                        .HasColumnName("fail_rate");

                    b.Property<int>("ScansLast24h")
                        .HasColumnType("integer")
                        .HasColumnName("scans_last_24h");

                    b.Property<decimal>("SuccessRate")
                        .HasColumnType("numeric")
                        .HasColumnName("success_rate");

                    b.Property<int>("TotalScans")
                        .HasColumnType("integer")
                        .HasColumnName("total_scans");

                    b.ToTable((string)null);

                    b.ToView("vw_dashboard_scan_stats", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Infrastructure.Data.Views.ViewModels.DashboardScanTrendDaily", b =>
                {
                    b.Property<int>("FailedScans")
                        .HasColumnType("integer")
                        .HasColumnName("failed_scans");

                    b.Property<int>("ScanCount")
                        .HasColumnType("integer")
                        .HasColumnName("scan_count");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scan_date");

                    b.Property<int>("SuccessfulScans")
                        .HasColumnType("integer")
                        .HasColumnName("successful_scans");

                    b.ToTable((string)null);

                    b.ToView("vw_dashboard_scan_trend_daily", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Infrastructure.Data.Views.ViewModels.DashboardUserRegistrationTrend", b =>
                {
                    b.Property<int>("NewUsers")
                        .HasColumnType("integer")
                        .HasColumnName("new_users");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.ToTable((string)null);

                    b.ToView("vw_dashboard_user_registration_trend", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Infrastructure.Data.Views.ViewModels.DashboardUserStats", b =>
                {
                    b.Property<int>("ActiveUsers")
                        .HasColumnType("integer")
                        .HasColumnName("active_users");

                    b.Property<int>("BlockedUsers")
                        .HasColumnType("integer")
                        .HasColumnName("blocked_users");

                    b.Property<int>("NewUsersLast30Days")
                        .HasColumnType("integer")
                        .HasColumnName("new_users_last_30_days");

                    b.Property<int>("NewUsersLast7Days")
                        .HasColumnType("integer")
                        .HasColumnName("new_users_last_7_days");

                    b.Property<int>("TotalUsers")
                        .HasColumnType("integer")
                        .HasColumnName("total_users");

                    b.ToTable((string)null);

                    b.ToView("vw_dashboard_user_stats", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Infrastructure.Data.Views.ViewModels.UserFindingsSummary", b =>
                {
                    b.Property<decimal>("PercentCritical")
                        .HasColumnType("numeric")
                        .HasColumnName("percent_critical");

                    b.Property<decimal>("PercentHigh")
                        .HasColumnType("numeric")
                        .HasColumnName("percent_high");

                    b.Property<decimal>("PercentInformational")
                        .HasColumnType("numeric")
                        .HasColumnName("percent_informational");

                    b.Property<decimal>("PercentLow")
                        .HasColumnType("numeric")
                        .HasColumnName("percent_low");

                    b.Property<decimal>("PercentMedium")
                        .HasColumnType("numeric")
                        .HasColumnName("percent_medium");

                    b.Property<int>("TotalCritical")
                        .HasColumnType("integer")
                        .HasColumnName("total_critical");

                    b.Property<int>("TotalFindings")
                        .HasColumnType("integer")
                        .HasColumnName("total_findings");

                    b.Property<int>("TotalHigh")
                        .HasColumnType("integer")
                        .HasColumnName("total_high");

                    b.Property<int>("TotalInformational")
                        .HasColumnType("integer")
                        .HasColumnName("total_informational");

                    b.Property<int>("TotalLow")
                        .HasColumnType("integer")
                        .HasColumnName("total_low");

                    b.Property<int>("TotalMedium")
                        .HasColumnType("integer")
                        .HasColumnName("total_medium");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("vw_user_findings_summary", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Infrastructure.Data.Views.ViewModels.UserScanSummary", b =>
                {
                    b.Property<double>("AvgScanDurationSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_scan_duration_seconds");

                    b.Property<int>("CompletedScans")
                        .HasColumnType("integer")
                        .HasColumnName("completed_scans");

                    b.Property<int>("FailedScans")
                        .HasColumnType("integer")
                        .HasColumnName("failed_scans");

                    b.Property<DateTime?>("LastScanDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scan_date");

                    b.Property<int>("ScansLast30Days")
                        .HasColumnType("integer")
                        .HasColumnName("scans_last_30_days");

                    b.Property<int>("ScansLast7Days")
                        .HasColumnType("integer")
                        .HasColumnName("scans_last_7_days");

                    b.Property<int>("TotalScans")
                        .HasColumnType("integer")
                        .HasColumnName("total_scans");

                    b.Property<int>("UniqueTargets")
                        .HasColumnType("integer")
                        .HasColumnName("unique_targets");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("vw_user_scan_summary", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("HeimdallWeb.Domain.Entities.ScanHistory", "History")
                        .WithMany("AuditLogs")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeimdallWeb.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("History");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.Finding", b =>
                {
                    b.HasOne("HeimdallWeb.Domain.Entities.ScanHistory", "History")
                        .WithMany("Findings")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.IASummary", b =>
                {
                    b.HasOne("HeimdallWeb.Domain.Entities.ScanHistory", "History")
                        .WithMany("IASummaries")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.ScanHistory", b =>
                {
                    b.HasOne("HeimdallWeb.Domain.Entities.User", "User")
                        .WithMany("ScanHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.Technology", b =>
                {
                    b.HasOne("HeimdallWeb.Domain.Entities.ScanHistory", "History")
                        .WithMany("Technologies")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.UserUsage", b =>
                {
                    b.HasOne("HeimdallWeb.Domain.Entities.User", "User")
                        .WithMany("UserUsages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.ScanHistory", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Findings");

                    b.Navigation("IASummaries");

                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ScanHistories");

                    b.Navigation("UserUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
