// <auto-generated />
using System;
using HeimdallWeb.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HeimdallWeb.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("code");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<int?>("HistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Info")
                        .HasColumnName("level");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("RemoteIp")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("remote_ip");

                    b.Property<string>("Source")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("LogId")
                        .HasName("pk_tb_log");

                    b.HasIndex("Code")
                        .HasDatabaseName("ix_tb_log_code");

                    b.HasIndex("HistoryId")
                        .HasDatabaseName("ix_tb_log_history_id");

                    b.HasIndex("Level")
                        .HasDatabaseName("ix_tb_log_level");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_tb_log_timestamp");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tb_log_user_id");

                    b.ToTable("tb_log", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.Finding", b =>
                {
                    b.Property<int>("FindingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("finding_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FindingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evidence");

                    b.Property<int?>("HistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("recommendation");

                    b.Property<short>("Severity")
                        .HasColumnType("smallint")
                        .HasColumnName("severity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("FindingId")
                        .HasName("pk_tb_finding");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tb_finding_created_at");

                    b.HasIndex("HistoryId")
                        .HasDatabaseName("ix_tb_finding_history_id");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_tb_finding_severity");

                    b.ToTable("tb_finding", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.IASummary", b =>
                {
                    b.Property<int>("IASummaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ia_summary_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IASummaryId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<int>("FindingsCritical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_critical");

                    b.Property<int>("FindingsHigh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_high");

                    b.Property<int>("FindingsLow")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_low");

                    b.Property<int>("FindingsMedium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_medium");

                    b.Property<int?>("HistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    b.Property<string>("IANotes")
                        .HasColumnType("text")
                        .HasColumnName("ia_notes");

                    b.Property<string>("MainCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("main_category");

                    b.Property<string>("OverallRisk")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("overall_risk");

                    b.Property<string>("SummaryText")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary_text");

                    b.Property<int>("TotalFindings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("total_findings");

                    b.HasKey("IASummaryId")
                        .HasName("pk_tb_ia_summary");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_tb_ia_summary_created_date");

                    b.HasIndex("HistoryId")
                        .HasDatabaseName("ix_tb_ia_summary_history_id");

                    b.HasIndex("MainCategory")
                        .HasDatabaseName("ix_tb_ia_summary_main_category");

                    b.HasIndex("OverallRisk")
                        .HasDatabaseName("ix_tb_ia_summary_overall_risk");

                    b.ToTable("tb_ia_summary", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.ScanHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval")
                        .HasColumnName("duration");

                    b.Property<bool>("HasCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_completed");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<string>("RawJsonResult")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_json_result");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("target");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("HistoryId")
                        .HasName("pk_tb_history");

                    b.HasIndex("CreatedDate")
                        .HasDatabaseName("ix_tb_history_created_date");

                    b.HasIndex("HasCompleted")
                        .HasDatabaseName("ix_tb_history_has_completed");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_tb_history_public_id");

                    b.HasIndex("RawJsonResult")
                        .HasDatabaseName("ix_tb_history_raw_json_gin");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("RawJsonResult"), "gin");

                    b.HasIndex("Target")
                        .HasDatabaseName("ix_tb_history_target");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tb_history_user_id");

                    b.ToTable("tb_history", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.Technology", b =>
                {
                    b.Property<int>("TechnologyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("technology_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TechnologyId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("technology_category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("technology_description");

                    b.Property<int?>("HistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("technology_name");

                    b.Property<string>("Version")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("version");

                    b.HasKey("TechnologyId")
                        .HasName("pk_tb_technology");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_tb_technology_category");

                    b.HasIndex("HistoryId")
                        .HasDatabaseName("ix_tb_technology_history_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_tb_technology_name");

                    b.ToTable("tb_technology", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("profile_image");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("uuid")
                        .HasColumnName("public_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("user_type");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_tb_user");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_tb_user_created_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_tb_user_email");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ux_tb_user_public_id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_tb_user_username");

                    b.ToTable("tb_user", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.UserUsage", b =>
                {
                    b.Property<int>("UserUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_usage_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserUsageId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("RequestCounts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("request_counts");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("UserUsageId")
                        .HasName("pk_tb_user_usage");

                    b.HasIndex("Date")
                        .HasDatabaseName("ix_tb_user_usage_date");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_tb_user_usage_user_id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_tb_user_usage_user_id_date");

                    b.ToTable("tb_user_usage", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.Views.UserCategoryBreakdown", b =>
                {
                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<int>("CategoryCount")
                        .HasColumnType("integer")
                        .HasColumnName("category_count");

                    b.Property<int>("CriticalInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("critical_in_category");

                    b.Property<int>("HighInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("high_in_category");

                    b.Property<int>("InformationalInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("informational_in_category");

                    b.Property<int>("LowInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("low_in_category");

                    b.Property<int>("MediumInCategory")
                        .HasColumnType("integer")
                        .HasColumnName("medium_in_category");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("vw_user_category_breakdown", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.Views.UserRiskTrend", b =>
                {
                    b.Property<int>("CriticalCount")
                        .HasColumnType("integer")
                        .HasColumnName("critical_count");

                    b.Property<int>("HighCount")
                        .HasColumnType("integer")
                        .HasColumnName("high_count");

                    b.Property<int>("InformationalCount")
                        .HasColumnType("integer")
                        .HasColumnName("informational_count");

                    b.Property<int>("LowCount")
                        .HasColumnType("integer")
                        .HasColumnName("low_count");

                    b.Property<int>("MediumCount")
                        .HasColumnType("integer")
                        .HasColumnName("medium_count");

                    b.Property<DateTime>("RiskDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("risk_date");

                    b.Property<int>("ScansOnDate")
                        .HasColumnType("integer")
                        .HasColumnName("scans_on_date");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("vw_user_risk_trend", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("HeimdallWeb.Domain.Entities.ScanHistory", "History")
                        .WithMany("AuditLogs")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeimdallWeb.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("History");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.Finding", b =>
                {
                    b.HasOne("HeimdallWeb.Domain.Entities.ScanHistory", "History")
                        .WithMany("Findings")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.IASummary", b =>
                {
                    b.HasOne("HeimdallWeb.Domain.Entities.ScanHistory", "History")
                        .WithMany("IASummaries")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.ScanHistory", b =>
                {
                    b.HasOne("HeimdallWeb.Domain.Entities.User", "User")
                        .WithMany("ScanHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.Technology", b =>
                {
                    b.HasOne("HeimdallWeb.Domain.Entities.ScanHistory", "History")
                        .WithMany("Technologies")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.UserUsage", b =>
                {
                    b.HasOne("HeimdallWeb.Domain.Entities.User", "User")
                        .WithMany("UserUsages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.ScanHistory", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Findings");

                    b.Navigation("IASummaries");

                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("HeimdallWeb.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ScanHistories");

                    b.Navigation("UserUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
