CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE tb_user (
    user_id integer GENERATED BY DEFAULT AS IDENTITY,
    username character varying(30) NOT NULL,
    email character varying(75) NOT NULL,
    password character varying(255) NOT NULL,
    user_type integer NOT NULL DEFAULT 1,
    is_active boolean NOT NULL DEFAULT TRUE,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone,
    profile_image character varying(255),
    CONSTRAINT pk_tb_user PRIMARY KEY (user_id)
);

CREATE TABLE tb_history (
    history_id integer GENERATED BY DEFAULT AS IDENTITY,
    target character varying(75) NOT NULL,
    raw_json_result jsonb NOT NULL,
    summary text NOT NULL,
    has_completed boolean NOT NULL DEFAULT FALSE,
    duration interval,
    created_date timestamp with time zone NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT pk_tb_history PRIMARY KEY (history_id),
    CONSTRAINT "FK_tb_history_tb_user_user_id" FOREIGN KEY (user_id) REFERENCES tb_user (user_id) ON DELETE CASCADE
);

CREATE TABLE tb_user_usage (
    user_usage_id integer GENERATED BY DEFAULT AS IDENTITY,
    date date NOT NULL,
    request_counts integer NOT NULL DEFAULT 0,
    user_id integer NOT NULL,
    CONSTRAINT pk_tb_user_usage PRIMARY KEY (user_usage_id),
    CONSTRAINT "FK_tb_user_usage_tb_user_user_id" FOREIGN KEY (user_id) REFERENCES tb_user (user_id) ON DELETE CASCADE
);

CREATE TABLE tb_finding (
    finding_id integer GENERATED BY DEFAULT AS IDENTITY,
    type character varying(100) NOT NULL,
    description text NOT NULL,
    severity smallint NOT NULL,
    evidence text NOT NULL,
    recommendation character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    history_id integer,
    CONSTRAINT pk_tb_finding PRIMARY KEY (finding_id),
    CONSTRAINT "FK_tb_finding_tb_history_history_id" FOREIGN KEY (history_id) REFERENCES tb_history (history_id) ON DELETE CASCADE
);

CREATE TABLE tb_ia_summary (
    ia_summary_id integer GENERATED BY DEFAULT AS IDENTITY,
    summary_text character varying(1000),
    main_category character varying(100),
    overall_risk character varying(20),
    total_findings integer NOT NULL DEFAULT 0,
    findings_critical integer NOT NULL DEFAULT 0,
    findings_high integer NOT NULL DEFAULT 0,
    findings_medium integer NOT NULL DEFAULT 0,
    findings_low integer NOT NULL DEFAULT 0,
    ia_notes text,
    created_date timestamp with time zone NOT NULL,
    history_id integer,
    CONSTRAINT pk_tb_ia_summary PRIMARY KEY (ia_summary_id),
    CONSTRAINT "FK_tb_ia_summary_tb_history_history_id" FOREIGN KEY (history_id) REFERENCES tb_history (history_id) ON DELETE CASCADE
);

CREATE TABLE tb_log (
    log_id integer GENERATED BY DEFAULT AS IDENTITY,
    timestamp timestamp with time zone NOT NULL,
    code character varying(45) NOT NULL,
    level character varying(10) NOT NULL DEFAULT 'Info',
    source character varying(100),
    message character varying(500) NOT NULL,
    details text,
    user_id integer,
    history_id integer,
    remote_ip character varying(45),
    CONSTRAINT pk_tb_log PRIMARY KEY (log_id),
    CONSTRAINT "FK_tb_log_tb_history_history_id" FOREIGN KEY (history_id) REFERENCES tb_history (history_id) ON DELETE SET NULL,
    CONSTRAINT "FK_tb_log_tb_user_user_id" FOREIGN KEY (user_id) REFERENCES tb_user (user_id) ON DELETE SET NULL
);

CREATE TABLE tb_technology (
    technology_id integer GENERATED BY DEFAULT AS IDENTITY,
    technology_name character varying(100) NOT NULL,
    version character varying(30),
    technology_category character varying(50) NOT NULL,
    technology_description character varying(1000) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    history_id integer,
    CONSTRAINT pk_tb_technology PRIMARY KEY (technology_id),
    CONSTRAINT "FK_tb_technology_tb_history_history_id" FOREIGN KEY (history_id) REFERENCES tb_history (history_id) ON DELETE CASCADE
);

CREATE INDEX ix_tb_finding_created_at ON tb_finding (created_at);

CREATE INDEX ix_tb_finding_history_id ON tb_finding (history_id);

CREATE INDEX ix_tb_finding_severity ON tb_finding (severity);

CREATE INDEX ix_tb_history_created_date ON tb_history (created_date);

CREATE INDEX ix_tb_history_has_completed ON tb_history (has_completed);

CREATE INDEX ix_tb_history_raw_json_gin ON tb_history USING gin (raw_json_result);

CREATE INDEX ix_tb_history_target ON tb_history (target);

CREATE INDEX ix_tb_history_user_id ON tb_history (user_id);

CREATE INDEX ix_tb_ia_summary_created_date ON tb_ia_summary (created_date);

CREATE INDEX ix_tb_ia_summary_history_id ON tb_ia_summary (history_id);

CREATE INDEX ix_tb_ia_summary_main_category ON tb_ia_summary (main_category);

CREATE INDEX ix_tb_ia_summary_overall_risk ON tb_ia_summary (overall_risk);

CREATE INDEX ix_tb_log_code ON tb_log (code);

CREATE INDEX ix_tb_log_history_id ON tb_log (history_id);

CREATE INDEX ix_tb_log_level ON tb_log (level);

CREATE INDEX ix_tb_log_timestamp ON tb_log (timestamp);

CREATE INDEX ix_tb_log_user_id ON tb_log (user_id);

CREATE INDEX ix_tb_technology_category ON tb_technology (technology_category);

CREATE INDEX ix_tb_technology_history_id ON tb_technology (history_id);

CREATE INDEX ix_tb_technology_name ON tb_technology (technology_name);

CREATE INDEX ix_tb_user_created_at ON tb_user (created_at);

CREATE UNIQUE INDEX ux_tb_user_email ON tb_user (email);

CREATE UNIQUE INDEX ux_tb_user_username ON tb_user (username);

CREATE INDEX ix_tb_user_usage_date ON tb_user_usage (date);

CREATE INDEX ix_tb_user_usage_user_id ON tb_user_usage (user_id);

CREATE UNIQUE INDEX ix_tb_user_usage_user_id_date ON tb_user_usage (user_id, date);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260205222240_InitialPostgreSQLMigration', '10.0.2');

COMMIT;

