// <auto-generated />
using System;
using HeimdallWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeimdallWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115001302_campoCodeLogEnum")]
    partial class campoCodeLogEnum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HeimdallWebOld.Models.FindingModel", b =>
                {
                    b.Property<int>("finding_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("finding_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("evidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("text");

                    b.Property<int?>("history_id")
                        .HasColumnType("int");

                    b.Property<string>("recommendation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<sbyte>("severity")
                        .HasMaxLength(10)
                        .HasColumnType("TINYINT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("finding_id");

                    b.HasIndex("history_id");

                    b.ToTable("tb_finding");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.HistoryModel", b =>
                {
                    b.Property<int>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("history_id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan?>("duration")
                        .HasColumnType("time");

                    b.Property<bool>("has_completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("raw_json_result")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("target")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("history_id");

                    b.HasIndex("user_id");

                    b.ToTable("tb_history");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.IASummaryModel", b =>
                {
                    b.Property<int>("ia_summary_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ia_summary_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ia_summary_id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<int>("findings_critical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_critical");

                    b.Property<int>("findings_high")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_high");

                    b.Property<int>("findings_low")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_low");

                    b.Property<int>("findings_medium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_medium");

                    b.Property<int?>("history_id")
                        .HasColumnType("int")
                        .HasColumnName("history_id");

                    b.Property<string>("ia_notes")
                        .HasColumnType("text")
                        .HasColumnName("ia_notes");

                    b.Property<string>("main_category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("main_category");

                    b.Property<string>("overall_risk")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("ENUM('Baixo','Medio','Alto','Critico')")
                        .HasDefaultValue("Baixo")
                        .HasColumnName("overall_risk");

                    b.Property<string>("summary_text")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("summary_text");

                    b.Property<int>("total_findings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_findings");

                    b.HasKey("ia_summary_id")
                        .HasName("pk_tb_ia_summary");

                    b.HasIndex("history_id");

                    b.ToTable("tb_ia_summary", (string)null);
                });

            modelBuilder.Entity("HeimdallWebOld.Models.LogModel", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("log_id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code");

                    b.Property<string>("details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<int?>("history_id")
                        .HasColumnType("int")
                        .HasColumnName("history_id");

                    b.Property<string>("level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Info")
                        .HasColumnName("level");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<string>("remote_ip")
                        .HasColumnType("longtext");

                    b.Property<string>("source")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<int?>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("log_id")
                        .HasName("pk_tb_log");

                    b.HasIndex("history_id");

                    b.HasIndex("level")
                        .HasDatabaseName("ix_tb_log_level");

                    b.HasIndex("timestamp")
                        .HasDatabaseName("ix_tb_log_timestamp");

                    b.HasIndex("user_id");

                    b.ToTable("tb_log", (string)null);
                });

            modelBuilder.Entity("HeimdallWebOld.Models.TechnologyModel", b =>
                {
                    b.Property<int>("technology_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("technology_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("history_id")
                        .HasColumnType("int");

                    b.Property<string>("technology_category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("technology_description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("technology_name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)");

                    b.Property<string>("version")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("technology_id");

                    b.HasIndex("history_id");

                    b.ToTable("tb_technology");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.UserModel", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("user_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("email");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("user_type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("user_type");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("username");

                    b.HasKey("user_id")
                        .HasName("pk_tb_user");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasDatabaseName("ux_tb_user_email");

                    b.HasIndex("username")
                        .IsUnique()
                        .HasDatabaseName("ux_tb_user_username");

                    b.ToTable("tb_user", (string)null);
                });

            modelBuilder.Entity("HeimdallWebOld.Models.UserUsageModel", b =>
                {
                    b.Property<int>("user_usage_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_usage_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("user_usage_id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int>("request_counts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("request_counts");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("user_usage_id")
                        .HasName("pk_tb_user_usage");

                    b.HasIndex("user_id");

                    b.ToTable("tb_user_usage", (string)null);
                });

            modelBuilder.Entity("HeimdallWebOld.Models.FindingModel", b =>
                {
                    b.HasOne("HeimdallWebOld.Models.HistoryModel", "History")
                        .WithMany("Findings")
                        .HasForeignKey("history_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.HistoryModel", b =>
                {
                    b.HasOne("HeimdallWebOld.Models.UserModel", "User")
                        .WithMany("Histories")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.IASummaryModel", b =>
                {
                    b.HasOne("HeimdallWebOld.Models.HistoryModel", "History")
                        .WithMany("IASummaries")
                        .HasForeignKey("history_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.LogModel", b =>
                {
                    b.HasOne("HeimdallWebOld.Models.HistoryModel", "History")
                        .WithMany("Logs")
                        .HasForeignKey("history_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HeimdallWebOld.Models.UserModel", "User")
                        .WithMany("LogModel")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.TechnologyModel", b =>
                {
                    b.HasOne("HeimdallWebOld.Models.HistoryModel", "History")
                        .WithMany("Technologies")
                        .HasForeignKey("history_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.UserUsageModel", b =>
                {
                    b.HasOne("HeimdallWebOld.Models.UserModel", "User")
                        .WithMany("UserUsages")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.HistoryModel", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("IASummaries");

                    b.Navigation("Logs");

                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.UserModel", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("LogModel");

                    b.Navigation("UserUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
