// <auto-generated />
using System;
using HeimdallWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeimdallWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250917005934_AddFindingTable")]
    partial class AddFindingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HeimdallWebOld.Models.FindingModel", b =>
                {
                    b.Property<int>("finding_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("finding_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("evidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("text");

                    b.Property<int?>("history_id")
                        .HasColumnType("int");

                    b.Property<string>("recommendation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("ENUM('Low','Medium','High','Critical')");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("finding_id");

                    b.HasIndex("history_id");

                    b.ToTable("tb_finding");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.HistoryModel", b =>
                {
                    b.Property<int>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("history_id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("raw_json_result")
                        .HasColumnType("json");

                    b.Property<string>("summary")
                        .HasColumnType("longtext");

                    b.Property<string>("target")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.HasKey("history_id");

                    b.HasIndex("user_id");

                    b.ToTable("tb_history");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.IASummaryModel", b =>
                {
                    b.Property<int>("ia_summary_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ia_summary_id"));

                    b.Property<string>("category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("history_id")
                        .HasColumnType("int");

                    b.Property<string>("issue")
                        .HasColumnType("longtext");

                    b.Property<string>("recommendation")
                        .HasColumnType("longtext");

                    b.HasKey("ia_summary_id");

                    b.HasIndex("history_id");

                    b.ToTable("tb_ia_summary");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.TechnologyModel", b =>
                {
                    b.Property<int>("technology_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("technology_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("history_id")
                        .HasColumnType("int");

                    b.Property<string>("technology_name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)");

                    b.Property<string>("version")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("technology_id");

                    b.HasIndex("history_id");

                    b.ToTable("tb_technology");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.UserModel", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("user_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("user_type")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("user_id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("tb_user");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.FindingModel", b =>
                {
                    b.HasOne("HeimdallWebOld.Models.HistoryModel", "History")
                        .WithMany("Findings")
                        .HasForeignKey("history_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.HistoryModel", b =>
                {
                    b.HasOne("HeimdallWebOld.Models.UserModel", "User")
                        .WithMany("Histories")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.IASummaryModel", b =>
                {
                    b.HasOne("HeimdallWebOld.Models.HistoryModel", "History")
                        .WithMany("IASummaries")
                        .HasForeignKey("history_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.TechnologyModel", b =>
                {
                    b.HasOne("HeimdallWebOld.Models.HistoryModel", "History")
                        .WithMany("Technologies")
                        .HasForeignKey("history_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.HistoryModel", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("IASummaries");

                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("HeimdallWebOld.Models.UserModel", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
