export enum SeverityLevel {
  Informational = 0,
  Low = 1,
  Medium = 2,
  High = 3,
  Critical = 4,
}

export enum UserType {
  Default = 1,
  Admin = 2,
}

export enum LogEventCode {
  INIT_SCAN = "INIT_SCAN",
  SCAN_COMPLETED = "SCAN_COMPLETED",
  SCAN_ERROR = "SCAN_ERROR",
  AI_REQUEST = "AI_REQUEST",
  AI_RESPONSE = "AI_RESPONSE",
  AI_RESPONSE_ERROR = "AI_RESPONSE_ERROR",
  PATH_SCAN_STARTED = "PATH_SCAN_STARTED",
  PATH_SCAN_RESULT = "PATH_SCAN_RESULT",
  PATH_SUSPECTED_FALLBACK = "PATH_SUSPECTED_FALLBACK",
  HEADER_SCAN = "HEADER_SCAN",
  COOKIE_SCAN = "COOKIE_SCAN",
  SSL_SCAN = "SSL_SCAN",
  DB_SAVE_OK = "DB_SAVE_OK",
  DB_SAVE_ERROR = "DB_SAVE_ERROR",
  USER_LOGIN = "USER_LOGIN",
  USER_LOGIN_FAILED = "USER_LOGIN_FAILED",
  USER_REGISTERED = "USER_REGISTERED",
  USER_REGISTRATION_FAILED = "USER_REGISTRATION_FAILED",
  USER_PROFILE_UPDATED = "USER_PROFILE_UPDATED",
  USER_PASSWORD_CHANGED = "USER_PASSWORD_CHANGED",
  USER_ACCOUNT_DELETED = "USER_ACCOUNT_DELETED",
  SCAN_HISTORY_DELETED = "SCAN_HISTORY_DELETED",
  USER_STATUS_TOGGLED = "USER_STATUS_TOGGLED",
  USER_DELETED_BY_ADMIN = "USER_DELETED_BY_ADMIN",
  PROFILE_IMAGE_UPDATED = "PROFILE_IMAGE_UPDATED",
  UNHANDLED_EXCEPTION = "UNHANDLED_EXCEPTION",
}
