// <auto-generated />
using System;
using HeimdallWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HeimdallWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260203234417_UpdateDescriptionField")]
    partial class UpdateDescriptionField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HeimdallWeb.Models.AdminIASummaryStats", b =>
                {
                    b.Property<decimal>("avg_findings_per_scan")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("critical_last_24h")
                        .HasColumnType("bigint");

                    b.Property<long>("high_last_24h")
                        .HasColumnType("bigint");

                    b.Property<int>("scans_critical_risk")
                        .HasColumnType("int");

                    b.Property<int>("scans_high_risk")
                        .HasColumnType("int");

                    b.Property<int>("scans_low_risk")
                        .HasColumnType("int");

                    b.Property<int>("scans_medium_risk")
                        .HasColumnType("int");

                    b.Property<long>("total_critical")
                        .HasColumnType("bigint");

                    b.Property<long>("total_findings_all_scans")
                        .HasColumnType("bigint");

                    b.Property<long>("total_high")
                        .HasColumnType("bigint");

                    b.Property<long>("total_low")
                        .HasColumnType("bigint");

                    b.Property<long>("total_medium")
                        .HasColumnType("bigint");

                    b.ToTable((string)null);

                    b.ToView("vw_admin_ia_summary_stats", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.AdminMostVulnerableTarget", b =>
                {
                    b.Property<string>("highest_risk_level")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("last_scan_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("scan_count")
                        .HasColumnType("int");

                    b.Property<string>("target")
                        .HasColumnType("longtext");

                    b.Property<int>("total_critical")
                        .HasColumnType("int");

                    b.Property<int>("total_findings")
                        .HasColumnType("int");

                    b.Property<int>("total_high")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_admin_most_vulnerable_targets", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.AdminRiskDistributionDaily", b =>
                {
                    b.Property<int>("critical_findings")
                        .HasColumnType("int");

                    b.Property<int>("high_findings")
                        .HasColumnType("int");

                    b.Property<int>("low_findings")
                        .HasColumnType("int");

                    b.Property<int>("medium_findings")
                        .HasColumnType("int");

                    b.Property<DateTime>("risk_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("total_summaries")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_admin_risk_distribution_daily", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.AdminTopCategory", b =>
                {
                    b.Property<int>("category_occurrences")
                        .HasColumnType("int");

                    b.Property<int>("critical_in_category")
                        .HasColumnType("int");

                    b.Property<int>("high_in_category")
                        .HasColumnType("int");

                    b.Property<string>("main_category")
                        .HasColumnType("longtext");

                    b.Property<decimal>("percentage_of_total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("total_findings_in_category")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_admin_top_categories", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.DashboardLogsOverview", b =>
                {
                    b.Property<int>("logs_errors_last_24h")
                        .HasColumnType("int");

                    b.Property<int>("logs_info_last_24h")
                        .HasColumnType("int");

                    b.Property<int>("logs_today")
                        .HasColumnType("int");

                    b.Property<int>("logs_warn_last_24h")
                        .HasColumnType("int");

                    b.Property<int>("total_logs")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_dashboard_logs_overview", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.DashboardRecentActivity", b =>
                {
                    b.Property<string>("level")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("remote_ip")
                        .HasColumnType("longtext");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("user_id")
                        .HasColumnType("int");

                    b.Property<string>("username")
                        .HasColumnType("longtext");

                    b.ToTable((string)null);

                    b.ToView("vw_dashboard_recent_activity", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.DashboardScanStats", b =>
                {
                    b.Property<double>("avg_scan_time_s")
                        .HasColumnType("double");

                    b.Property<decimal>("fail_rate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("scans_last_24h")
                        .HasColumnType("int");

                    b.Property<decimal>("success_rate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("total_scans")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_dashboard_scan_stats", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.DashboardScanTrendDaily", b =>
                {
                    b.Property<int>("failed_scans")
                        .HasColumnType("int");

                    b.Property<int>("scan_count")
                        .HasColumnType("int");

                    b.Property<DateTime>("scan_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("successful_scans")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_dashboard_scan_trend_daily", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.DashboardUserRegistrationTrend", b =>
                {
                    b.Property<int>("new_users")
                        .HasColumnType("int");

                    b.Property<DateTime>("registration_date")
                        .HasColumnType("datetime(6)");

                    b.ToTable((string)null);

                    b.ToView("vw_dashboard_user_registration_trend", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.DashboardUserStats", b =>
                {
                    b.Property<int>("active_users")
                        .HasColumnType("int");

                    b.Property<int>("blocked_users")
                        .HasColumnType("int");

                    b.Property<int>("new_users_last_30_days")
                        .HasColumnType("int");

                    b.Property<int>("new_users_last_7_days")
                        .HasColumnType("int");

                    b.Property<int>("total_users")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_dashboard_user_stats", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.FindingModel", b =>
                {
                    b.Property<int>("finding_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("finding_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("evidence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("text");

                    b.Property<int?>("history_id")
                        .HasColumnType("int");

                    b.Property<string>("recommendation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<sbyte>("severity")
                        .HasMaxLength(10)
                        .HasColumnType("TINYINT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("finding_id");

                    b.HasIndex("history_id");

                    b.ToTable("tb_finding");
                });

            modelBuilder.Entity("HeimdallWeb.Models.HistoryModel", b =>
                {
                    b.Property<int>("history_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("history_id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan?>("duration")
                        .HasColumnType("time");

                    b.Property<bool>("has_completed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("raw_json_result")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("target")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("history_id");

                    b.HasIndex("user_id");

                    b.ToTable("tb_history");
                });

            modelBuilder.Entity("HeimdallWeb.Models.IASummaryModel", b =>
                {
                    b.Property<int>("ia_summary_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ia_summary_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ia_summary_id"));

                    b.Property<DateTime>("created_date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_date");

                    b.Property<int>("findings_critical")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_critical");

                    b.Property<int>("findings_high")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_high");

                    b.Property<int>("findings_low")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_low");

                    b.Property<int>("findings_medium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("findings_medium");

                    b.Property<int?>("history_id")
                        .HasColumnType("int")
                        .HasColumnName("history_id");

                    b.Property<string>("ia_notes")
                        .HasColumnType("text")
                        .HasColumnName("ia_notes");

                    b.Property<string>("main_category")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("main_category");

                    b.Property<string>("overall_risk")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("ENUM('Baixo','Medio','Alto','Critico')")
                        .HasDefaultValue("Baixo")
                        .HasColumnName("overall_risk");

                    b.Property<string>("summary_text")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("summary_text");

                    b.Property<int>("total_findings")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("total_findings");

                    b.HasKey("ia_summary_id")
                        .HasName("pk_tb_ia_summary");

                    b.HasIndex("history_id");

                    b.ToTable("tb_ia_summary", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.LogModel", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("log_id"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("varchar(45)")
                        .HasColumnName("code");

                    b.Property<string>("details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<int?>("history_id")
                        .HasColumnType("int")
                        .HasColumnName("history_id");

                    b.Property<string>("level")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Info")
                        .HasColumnName("level");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<string>("remote_ip")
                        .HasColumnType("longtext");

                    b.Property<string>("source")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("source");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<int?>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("log_id")
                        .HasName("pk_tb_log");

                    b.HasIndex("history_id");

                    b.HasIndex("level")
                        .HasDatabaseName("ix_tb_log_level");

                    b.HasIndex("timestamp")
                        .HasDatabaseName("ix_tb_log_timestamp");

                    b.HasIndex("user_id");

                    b.ToTable("tb_log", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.TechnologyModel", b =>
                {
                    b.Property<int>("technology_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("technology_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("history_id")
                        .HasColumnType("int");

                    b.Property<string>("technology_category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("technology_description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("technology_name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("varchar(35)");

                    b.Property<string>("version")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("technology_id");

                    b.HasIndex("history_id");

                    b.ToTable("tb_technology");
                });

            modelBuilder.Entity("HeimdallWeb.Models.UserCategoryBreakdown", b =>
                {
                    b.Property<int>("category_count")
                        .HasColumnType("int");

                    b.Property<int>("critical_in_category")
                        .HasColumnType("int");

                    b.Property<int>("high_in_category")
                        .HasColumnType("int");

                    b.Property<int>("low_in_category")
                        .HasColumnType("int");

                    b.Property<string>("main_category")
                        .HasColumnType("longtext");

                    b.Property<int>("medium_in_category")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_user_category_breakdown", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.UserFindingsSummary", b =>
                {
                    b.Property<decimal>("percent_critical")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("percent_high")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("percent_low")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("percent_medium")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("total_critical")
                        .HasColumnType("int");

                    b.Property<int>("total_findings")
                        .HasColumnType("int");

                    b.Property<int>("total_high")
                        .HasColumnType("int");

                    b.Property<int>("total_low")
                        .HasColumnType("int");

                    b.Property<int>("total_medium")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_user_findings_summary", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.UserModel", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("user_id"));

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("varchar(75)")
                        .HasColumnName("email");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("profile_image")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("profile_image");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("user_type")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("user_type");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("username");

                    b.HasKey("user_id")
                        .HasName("pk_tb_user");

                    b.HasIndex("email")
                        .IsUnique()
                        .HasDatabaseName("ux_tb_user_email");

                    b.HasIndex("username")
                        .IsUnique()
                        .HasDatabaseName("ux_tb_user_username");

                    b.ToTable("tb_user", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.UserRiskTrend", b =>
                {
                    b.Property<int>("critical_count")
                        .HasColumnType("int");

                    b.Property<int>("high_count")
                        .HasColumnType("int");

                    b.Property<int>("low_count")
                        .HasColumnType("int");

                    b.Property<int>("medium_count")
                        .HasColumnType("int");

                    b.Property<DateTime>("risk_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("scans_on_date")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_user_risk_trend", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.UserScanSummary", b =>
                {
                    b.Property<decimal?>("avg_scan_duration_seconds")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("completed_scans")
                        .HasColumnType("int");

                    b.Property<int>("failed_scans")
                        .HasColumnType("int");

                    b.Property<DateTime?>("last_scan_date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("scans_last_30_days")
                        .HasColumnType("int");

                    b.Property<int>("scans_last_7_days")
                        .HasColumnType("int");

                    b.Property<int>("total_scans")
                        .HasColumnType("int");

                    b.Property<int>("unique_targets")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("vw_user_scan_summary", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.UserUsageModel", b =>
                {
                    b.Property<int>("user_usage_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_usage_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("user_usage_id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("date");

                    b.Property<int>("request_counts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("request_counts");

                    b.Property<int>("user_id")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("user_usage_id")
                        .HasName("pk_tb_user_usage");

                    b.HasIndex("user_id");

                    b.ToTable("tb_user_usage", (string)null);
                });

            modelBuilder.Entity("HeimdallWeb.Models.FindingModel", b =>
                {
                    b.HasOne("HeimdallWeb.Models.HistoryModel", "History")
                        .WithMany("Findings")
                        .HasForeignKey("history_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWeb.Models.HistoryModel", b =>
                {
                    b.HasOne("HeimdallWeb.Models.UserModel", "User")
                        .WithMany("Histories")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeimdallWeb.Models.IASummaryModel", b =>
                {
                    b.HasOne("HeimdallWeb.Models.HistoryModel", "History")
                        .WithMany("IASummaries")
                        .HasForeignKey("history_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWeb.Models.LogModel", b =>
                {
                    b.HasOne("HeimdallWeb.Models.HistoryModel", "History")
                        .WithMany("Logs")
                        .HasForeignKey("history_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HeimdallWeb.Models.UserModel", "User")
                        .WithMany("LogModel")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("History");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeimdallWeb.Models.TechnologyModel", b =>
                {
                    b.HasOne("HeimdallWeb.Models.HistoryModel", "History")
                        .WithMany("Technologies")
                        .HasForeignKey("history_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("History");
                });

            modelBuilder.Entity("HeimdallWeb.Models.UserUsageModel", b =>
                {
                    b.HasOne("HeimdallWeb.Models.UserModel", "User")
                        .WithMany("UserUsages")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HeimdallWeb.Models.HistoryModel", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("IASummaries");

                    b.Navigation("Logs");

                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("HeimdallWeb.Models.UserModel", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("LogModel");

                    b.Navigation("UserUsages");
                });
#pragma warning restore 612, 618
        }
    }
}
