namespace HeimdallWeb.Application.Interfaces;

/// <summary>
/// Service for caching scan results to prevent redundant scans against the same target.
/// Cache keys are SHA-256 hashes of the normalized target URL + profile ID combination.
/// </summary>
public interface IScanCacheService
{
    /// <summary>
    /// Generates a deterministic 64-character hex cache key from the target URL and optional profile ID.
    /// </summary>
    /// <param name="target">Normalized target URL.</param>
    /// <param name="profileId">Optional scan profile ID. Null uses a default sentinel.</param>
    /// <returns>Lowercase hex SHA-256 digest (64 characters).</returns>
    string GenerateCacheKey(string target, int? profileId);

    /// <summary>
    /// Returns the cached JSON result for the given key if it exists and has not expired.
    /// </summary>
    /// <param name="cacheKey">Cache key generated by <see cref="GenerateCacheKey"/>.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>Cached result JSON string, or null if no valid cache entry exists.</returns>
    Task<string?> GetCachedResultAsync(string cacheKey, CancellationToken ct = default);

    /// <summary>
    /// Stores a scan result in the cache with the specified TTL.
    /// If an entry already exists for the key it is replaced.
    /// </summary>
    /// <param name="cacheKey">Cache key generated by <see cref="GenerateCacheKey"/>.</param>
    /// <param name="resultJson">Complete scan result serialized as JSON.</param>
    /// <param name="expiration">How long the cache entry should be valid.</param>
    /// <param name="ct">Cancellation token.</param>
    Task CacheResultAsync(string cacheKey, string resultJson, TimeSpan expiration, CancellationToken ct = default);

    /// <summary>
    /// Deletes all cache entries that have passed their expiration timestamp.
    /// Intended to be called periodically by the <see cref="HeimdallWeb.Application.Workers.MonitoringWorker"/>.
    /// </summary>
    /// <param name="ct">Cancellation token.</param>
    Task CleanupExpiredCacheAsync(CancellationToken ct = default);
}
